include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore
    directives_ordering: ignore