name: Dart CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Android NDK toolchain Setup
        uses: ravinderjangra/android-ndk-toolchain-setup@0.1
        with: 
          api: '21'
          arch: 'arm'
          install-location: 'toolchains'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.2'
          channel: 'stable'
      - run: echo $ANDROID_NDK_HOME
      - run: flutter packages get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        # Step to save the APK as Artifacts
      - name: Upload APK on Build Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: build/app/outputs/flutter-apk/app-release.apk
       
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.2'
          channel: 'stable'
      - run: flutter doctor -v
      - run: flutter packages get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
